version: '3.1'

services:
  db:
    image: mysql
    container_name: gazadatabase
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - spring-network

  app:
    image: junseok1204/gaza-server:0.0.1
    container_name: app-container
    ports:
      - 8080:8080
    env_file:
      - "./.env"
    environment:
      - Dcom.amazonaws.sdk.disableEc2Metadata=true
    depends_on:
      - db
    links:
      - db
    networks:
      - spring-network
    restart: always

networks:
  spring-network:

volumes:
  mysql-data:
