version: '3.8'

services:
  db:
    image: mysql
    container_name: gazadatabase
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wnstjr6522
      MYSQL_DATABASE: gaza
      MYSQL_ROOT_HOST: '%'
    networks:
      - spring-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app-container
    ports:
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gaza?characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "wnstjr6522"
    depends_on:
      - db
    links:
      - db
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data:
